#!/usr/bin/env python3

import os
from functions import *

if __name__ == "__main__":
    # Elevate script to root
    if not os.geteuid() == 0:
        sudo_args = ['sudo', sys.executable] + sys.argv + [os.environ]
        os.execlpe('sudo', *sudo_args)
    # Expand root partition to whole drive
    # read root partition mount
    root_part = bash("mount | grep ' / ' | cut -d' ' -f 1")
    root_part = root_part[:-1]  # get device "name"
    bash(f"growpart {root_part} 2")

    # Device specific things:
    match bash("sudo dmidecode --string system-product-name").lower():
        case "sona" | "laser":
            # Apply fix for display driver
            # TODO: Add multitouch support

            # copy systemd file from config
            cpfile("/usr/local/config/device-specific/sona_laser/touchscreen-fix.service",
                   "/etc/systemd/system/touchscreen-fix.service")
            # enable service
            bash("systemctl enable touchscreen-fix.service")

        # all Picasso/deli amd devices
        case "berknip" | "dirinboz" | "ezkinil" | "gumboz" | "morphius" | "vilboz" | "vilboz360" | "woomax":
            # Copy ucm config for amd audio
            mkdir("/usr/share/alsa/ucm2/AMD/acp3xalc5682m98")
            # cp ucm configs
            cpfile("/usr/local/config/device-specific/amd-ucm/HiFi.conf",
                   "/usr/share/alsa/ucm2/AMD/acp3xalc5682m98/HiFi.conf")
            cpfile("/usr/local/config/device-specific/amd-ucm/acp3xalc5682m98.conf",
                   "/usr/share/alsa/ucm2/AMD/acp3xalc5682m98/acp3xalc5682m98.conf")
            # create conf.d symlink
            mkdir("/usr/share/alsa/ucm2/conf.d/acp3xalc5682m98")
            bash("ln -s /usr/share/alsa/ucm2/AMD/acp3xalc5682m98/acp3xalc5682m98.conf "
                 "/usr/share/alsa/ucm2/conf.d/acp3xalc5682m98/acp3xalc5682m98.conf")

    # delete systemd service
    bash("systemctl disable postinstall.service")
    rmfile("/etc/systemd/system/postinstall.service")
