#!/usr/bin/env python3

import os
from shutil import rmtree as rmdir
from pathlib import Path
import sys
import argparse
from urllib.request import urlretrieve, urlopen
import subprocess as sp
from os import system as bash
from threading import Thread
from urllib.error import URLError
from time import sleep


# parse arguments from the cli. Only for testing/advanced use. 95% of the arguments are handled by the user_input script
def process_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--local-path', dest="local_path",
                        help="Local path for kernel files to use instead of downloading from github.")
    parser.add_argument("--dev", action="store_true", dest="dev_build", default=False,
                        help="Use kernels from latest dev build. May be unstable.")
    parser.add_argument("--alt", action="store_true", dest="alt", default=False,
                        help="Use alt kernel. Recommended for older devices.")
    parser.add_argument("--exp", action="store_true", dest="exp", default=False,
                        help="Use experimental 5.15 chromeos kernel. It is newer, but Google does not use "
                             "it in production yet.")
    parser.add_argument("--mainline", action="store_true", dest="mainline", default=False,
                        help="Use mainline linux kernel instead of modified chromeos kernel. Might provide more "
                             "functionality on newer devices.")
    return parser.parse_args()


# Clean /tmp from eupnea files
def prepare_host() -> None:
    print("\033[96m" + "Preparing host system" + "\033[0m", flush=True)

    print("Creating /tmp/eupnea-update", flush=True)
    rmdir("/tmp/eupnea-update", ignore_errors=True)
    Path("/tmp/eupnea-update").mkdir()

    print("Installing necessary packages", flush=True)
    # install cgpt and futility
    if os.path.exists("/usr/bin/apt"):
        bash("apt install cgpt vboot-kernel-utils -y")
    elif os.path.exists("/usr/bin/pacman"):
        bash("pacman -S cgpt vboot-utils --noconfirm")
    elif os.path.exists("/usr/bin/dnf"):
        bash("dnf install cgpt vboot-utils --assumeyes")
    else:
        print("\033[91m" + "cgpt and futility not found, please install them using your disotros package manager"
              + "\033[0m", flush=True)
        exit(1)


# download kernel files from GitHub
def download_kernel() -> None:
    print("\033[96m" + "Downloading kernel binaries from github" + "\033[0m", flush=True)
    if args.dev_build:
        url = "https://github.com/eupnea-linux/kernel/releases/download/dev-build/"
    else:
        url = "https://github.com/eupnea-linux/kernel/releases/latest/download/"
    try:
        if args.mainline:
            url = "https://github.com/eupnea-linux/mainline-kernel/releases/latest/download/"
            urlretrieve(f"{url}bzImage", filename="/tmp/eupnea-update/bzImage")
            urlretrieve(f"{url}modules.tar.xz", filename="/tmp/eupnea-update/modules.tar.xz")
        else:
            if args.alt:
                print("Downloading alt kernel", flush=True)
                urlretrieve(f"{url}bzImage-alt", filename="/tmp/eupnea-update/bzImage")
                urlretrieve(f"{url}modules-alt.tar.xz", filename="/tmp/eupnea-update/modules.tar.xz")
            elif args.exp:
                print("Downloading experimental 5.15 kernel", flush=True)
                urlretrieve(f"{url}bzImage-exp", filename="/tmp/eupnea-update/bzImage")
                urlretrieve(f"{url}modules-exp.tar.xz", filename="/tmp/eupnea-update/modules.tar.xz")
            else:
                urlretrieve(f"{url}bzImage", filename="/tmp/eupnea-update/bzImage")
                urlretrieve(f"{url}modules.tar.xz", filename="/tmp/eupnea-update/modules.tar.xz")
    except URLError:
        print("\033[91m" + "Failed to reach github. Check your internet connection and try again\033[0m", flush=True)
        exit(1)


# Configure distro agnostic options
def flash_kernel() -> None:
    print("\n\033[96m" + "Flashing new kernel" + "\033[0m", flush=True)

    print("Extracting kernel modules", flush=True)
    rmdir("/lib/modules", ignore_errors=True)
    Path("/lib/modules").mkdir(parents=True, exist_ok=True)

    # modules tar contains /lib/modules, so it's extracted to / and --skip-old-files is used to prevent overwriting
    # other files in /lib
    bash(f"tar xpf /tmp/eupnea-update/modules.tar.xz --skip-old-files -C / --checkpoint=.10000")
    print("", flush=True)  # break line after tar

    print("Extracting kernel headers", flush=True)
    # TODO: extract kernel headers
    print("", flush=True)  # break line

    # get uuid of rootfs partition
    rootfs_partuuid = sp.run([f"blkid -o value -s PARTUUID {device}2"], shell=True,
                             capture_output=True).stdout.decode("utf-8").strip()

    print("Downloading default command line from github", flush=True)
    try:
        temp_cmdline = urlopen(
            "https://raw.githubusercontent.com/eupnea-linux/eupnea/main/configs/kernel.flags").read().decode(
            "utf-8")
    except URLError:
        print("\033[91m" + "Failed to reach github. Fallback to hardcoded default cmdline" + "\033[0m", flush=True)
        temp_cmdline = "console=tty1 root=PARTUUID=${USB_ROOTFS} i915.modeset=1 rootwait rw fbcon=logo-pos:center" \
                       ",logo-count:1 loglevel=0 splash"
    # get partuuid of rootfs
    new_cmdline = temp_cmdline.replace("${USB_ROOTFS}", rootfs_partuuid)
    with open("kernel.flags", "w") as file:
        file.write(new_cmdline)

    print("Signing kernel", flush=True)
    bash("futility vbutil_kernel --arch x86_64 --version 1 --keyblock /usr/share/vboot/devkeys/kernel.keyblock"
         + " --signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk --bootloader kernel.flags" +
         " --config kernel.flags --vmlinuz /tmp/eupnea-update/bzImage --pack /tmp/eupnea-update/bzImage.signed")

    print("Flashing kernel", flush=True)
    bash(f"dd if=/tmp/eupnea-update/bzImage.signed of={device}1")


if __name__ == "__main__":
    # Elevate script to root
    if os.geteuid() != 0:
        args = ['sudo', sys.executable] + sys.argv + [os.environ]
        os.execlpe('sudo', *args)
    args = process_args()

    skip_version_question = False
    skip_dev_question = False

    if args.dev_build:
        print("\033[93m" + "Using dev release" + "\033[0m", flush=True)
        skip_dev_question = True
    if args.alt:
        print("\033[93m" + "Using alt kernel" + "\033[0m", flush=True)
        skip_version_question = True
    if args.exp:
        print("\033[93m" + "Using experimental kernel" + "\033[0m", flush=True)
        skip_version_question = True
    if args.mainline:
        print("\033[93m" + "Using mainline kernel" + "\033[0m", flush=True)
        skip_version_question = True
    if args.local_path:
        print("\033[93m" + "Using local path" + "\033[0m", flush=True)
        skip_version_question = True

    # read root partition mount
    root_part = sp.run("mount | grep ' / ' | cut -d' ' -f 1", shell=True, capture_output=True).stdout.decode(
        "utf-8").strip()
    device = root_part[:len(root_part) - 1]  # get device "name"

    if not skip_version_question:
        while True:
            print("\033[92m" + "Which kernel would you like to flash? Press enter for default\n\033[0m", flush=True)
            user_input = input(
                "\033[94m" + "Available options: stable(default), alt(for older devices), mainline(might work better on"
                             " newer devices, exp(experimental 5.15 kernel)" + "\033[0m" + "\n")
            match user_input:
                case "" | "stable" | "Stable" | "Default" | "default":
                    break
                case "alt" | "Alt":
                    args.alt = True
                    break
                case "mainline" | "Mainline":
                    args.mainline = True
                    break
                case "exp" | "Experimental" | "experimental" | "Exp":
                    args.exp = True
                    break
                case _:
                    print("\033[91m" + "Invalid option, check your spelling" + "\033[0m", flush=True)

    if not skip_dev_question:
        print("\033[92m" + "Would you like to the developer version of the kernel? Type yes or press Enter for no\n"
              + "\033[0m", flush=True)
        user_input = input(
            "\033[94m" + "Available options: stable(default), alt(for older devices), mainline(might work better on "
                         "newer devices, exp(experimental 5.15 kernel)" + "\033[0m" + "\n")
        if user_input == "yes":
            args.dev_build = True

    prepare_host()
    if args.local_path is None:
        # Print download progress in terminal
        t = Thread(target=download_kernel)
        t.start()
        sleep(1)
        while t.is_alive():
            print(".", end="", flush=True)
            sleep(1)
        print("", flush=True)
    else:
        if not args.local_path.endswith("/"):
            kernel_path = f"{args.local_path}/"
        else:
            kernel_path = args.local_path
        print("\033[96m" + "Using local kernel files" + "\033[0m", flush=True)
        bash(f"cp {kernel_path}bzImage /tmp/eupnea-update/bzImage")
        bash(f"cp {kernel_path}modules.tar.xz /tmp/eupnea-update/modules.tar.xz")

    flash_kernel()
    print("\033[92m" + "Kernel update complete!" + "\033[0m", flush=True)
