name: 📦 Breath Delivery System
on:
  push:
    paths:
      - "resources/*"
      - "kernel/*"
      - "**.conf"
      - ".github/workflows/*.yml"

jobs:
  main:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2
      - name: Generate Diff/Changelog
        run: |
          echo 'DIFF<<EOF' >> $GITHUB_ENV
          git diff HEAD^..HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::BreathDeliverySystem$(date +"%Y.%m.%d_%H-%M")"
      - name: Create output folder
        run: mkdir -v output
      - name: Building breath-base
        run: dpkg-deb -Z gzip -b resources/breath-base/debian output/breath-base.deb
      - name: Building breath-skylake
        run: dpkg-deb -Z gzip -b resources/breath-skylake/debian output/breath-skylake.deb
      - name: Building the standard (Release 101) Kernel
        run: cd kernel; bash build.sh chromeos-5.10;
      - name: Building the legacy SKL/KBL Kernel
        run: cd kernel; bash build.sh alt-chromeos-5.10;
      - name: Release kernel and bzImage
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: 📦 Breath Rebuild - ${{ github.event.head_commit.message }}
          body: |
            🛈 General Changes since the last release
            ```
            ${{ env.DIFF }}
            ```

            🚚 Breath Delivery System - Triggered by ${{ github.sha }} at ${{ github.event.repository.updated_at }}
          files: |
            kernel/bzImage*
            kernel/modules*
            output/*
